### ISSUE TITLE
微信使用iOS的原生分享会失败

### ISSUE THREAD

**Issue by lihk11** [liuchenx/SurgeConfig#4]
微信使用iOS的原生分享会失败，比如从AppStore 分享到微信，总是会分享失败。

**Comment by liuchenx** [comment]
取消屏蔽部分 鹅厂的分析域名

**Comment by lihk11** [comment]
把ipv6跳过就好了::ffff:0:0:0:0/1, ::ffff:128.0:0:0/1 ，添加以下内容
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, ::ffff:0:0:0:0/1, ::ffff:128.0:0:0/1
